/**
 * Invoice PDF Generator with GST support
 */

import { Invoice } from "@/types/accounting";
import { formatCurrency, CurrencyCode } from "@/lib/currency";

export function generateInvoicePDF(invoice: Invoice, orgName: string, currency: CurrencyCode) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const lineItemRows = invoice.lineItems
    .map(
      (li) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${li.name}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center">${li.quantity}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:right">${formatCurrency(li.price, currency)}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:right">${formatCurrency(li.total, currency)}</td>
      </tr>`
    )
    .join("");

  const taxRows = invoice.isInterstate
    ? `<div class="total-row"><span>IGST (${invoice.taxRate}%)</span><span>${formatCurrency(invoice.igstAmount || 0, currency)}</span></div>`
    : `<div class="total-row"><span>CGST (${invoice.taxRate / 2}%)</span><span>${formatCurrency(invoice.cgstAmount || 0, currency)}</span></div>
       <div class="total-row"><span>SGST (${invoice.taxRate / 2}%)</span><span>${formatCurrency(invoice.sgstAmount || 0, currency)}</span></div>`;

  const gstinRow = invoice.customerGstin
    ? `<div class="section"><div class="section-label">GSTIN</div><div class="section-value" style="font-family:monospace">${invoice.customerGstin}</div></div>`
    : '';

  const posRow = invoice.placeOfSupply
    ? `<div class="section"><div class="section-label">Place of Supply</div><div class="section-value">${invoice.placeOfSupply}${invoice.isInterstate ? ' (Inter-state)' : ' (Intra-state)'}</div></div>`
    : '';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${invoice.invoiceNumber}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color:#1a1a1a; padding:40px; max-width:800px; margin:0 auto; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:40px; }
    .company { font-size:24px; font-weight:700; }
    .invoice-meta { text-align:right; }
    .invoice-number { font-size:20px; font-weight:600; color:#6366f1; }
    .meta-row { font-size:13px; color:#6b7280; margin-top:4px; }
    .section { margin-bottom:12px; }
    .section-label { font-size:12px; color:#9ca3af; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:2px; }
    .section-value { font-size:15px; font-weight:500; }
    table { width:100%; border-collapse:collapse; margin:24px 0; }
    th { padding:10px 12px; text-align:left; font-size:12px; color:#6b7280; text-transform:uppercase; letter-spacing:0.05em; border-bottom:2px solid #e5e7eb; }
    th:nth-child(2) { text-align:center; }
    th:nth-child(3), th:nth-child(4) { text-align:right; }
    .totals { display:flex; flex-direction:column; align-items:flex-end; }
    .total-row { display:flex; justify-content:space-between; width:280px; padding:6px 0; font-size:14px; }
    .total-row.grand { border-top:2px solid #1a1a1a; padding-top:10px; margin-top:4px; font-size:16px; font-weight:700; }
    .status { display:inline-block; padding:4px 12px; border-radius:20px; font-size:12px; font-weight:600; text-transform:uppercase; }
    .status-paid { background:#dcfce7; color:#166534; }
    .status-draft { background:#f3f4f6; color:#4b5563; }
    .status-sent { background:#dbeafe; color:#1e40af; }
    .footer { margin-top:60px; padding-top:20px; border-top:1px solid #e5e7eb; text-align:center; font-size:12px; color:#9ca3af; }
    @media print { body { padding:20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div><div class="company">${orgName}</div></div>
    <div class="invoice-meta">
      <div class="invoice-number">${invoice.invoiceNumber}</div>
      <div class="meta-row">Date: ${new Date(invoice.createdAt).toLocaleDateString()}</div>
      <div class="meta-row"><span class="status status-${invoice.status}">${invoice.status}</span></div>
    </div>
  </div>

  <div class="section">
    <div class="section-label">Bill To</div>
    <div class="section-value">${invoice.customerName}</div>
  </div>
  ${gstinRow}
  ${posRow}

  <table>
    <thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead>
    <tbody>${lineItemRows}</tbody>
  </table>

  <div class="totals">
    <div class="total-row"><span>Subtotal</span><span>${formatCurrency(invoice.subtotal, currency)}</span></div>
    ${taxRows}
    <div class="total-row grand"><span>Total</span><span>${formatCurrency(invoice.total, currency)}</span></div>
  </div>

  <div class="footer">Generated by LedgerFlow &bull; ${new Date().toLocaleDateString()}</div>
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;

  printWindow.document.write(html);
  printWindow.document.close();
}
